version: '2'


services:

  web:
    image: nginx:latest
    container_name: ctf-sqli
    ports:
      - "8888:80"
    networks:
      sqliLAN:
        ipv4_address: 192.168.16.10
    volumes:
      - ./www_site:/www_site
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
      - mysql

      
  php:
    build: ./php/ 
    container_name: ctf-sqli_php
    networks:
      sqliLAN:
        ipv4_address: 192.168.16.11
    volumes:
      - ./www_site:/www_site
    links:
      - mysql
    environment:
      READUSER_PASSWD: "qoeyjmdgpzybhqcy"


  mysql:
    build: ./mysql/
    container_name: ctf-sqli_mysql
    networks:
      sqliLAN:
        ipv4_address: 192.168.16.12
    environment:
      MYSQL_ROOT_PASSWORD: "azafgzazaz"
      READUSER_PASSWD: "qoeyjmdgpzybhqcy"

  attack:
    build: ./myattacksql/
    container_name: ctf-sqli_attack
    networks:
      sqliLAN:
        ipv4_address: 192.168.16.250
    links:
      - web
      
      
networks:
  sqliLAN:
    external: true
